"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, Check, Copy, Download, FileText, Layers3, LoaderCircle, Plus, ScanLine, Trash2, Upload } from "lucide-react";

type Status = "review" | "approved" | "excluded";
type Item = { id:string; reference:string; category:string; width:string; height:string; quantity:string; specification:string; features:string; sourcePage:number; sourceView:string; confidence:number; method:"Drawing text"|"Manual"; status:Status; warnings:string[] };
type PositionedText = { text:string; x:number; y:number; rotated:boolean };

const emptyItem=(id:string,page=1):Item=>({id,reference:`ITEM-${id}`,category:"Mirror",width:"",height:"",quantity:"1",specification:"",features:"",sourcePage:page,sourceView:"Manual takeoff",confidence:100,method:"Manual",status:"review",warnings:["Confirm dimensions and material specification"]});
function mode(values:number[]){const counts=new Map<number,number>();values.forEach((value)=>counts.set(value,(counts.get(value)??0)+1));return [...counts].sort((a,b)=>b[1]-a[1]||b[0]-a[0])[0]?.[0]}
function inferItems(tokens:PositionedText[],page:number):Item[]{
  const text=tokens.map((token)=>token.text).join(" ").replace(/\s+/g," ");const lower=text.toLowerCase();
  const dimensions=tokens.map((token)=>({token,value:Number(token.text.replace(/[^0-9.]/g,""))})).filter(({token,value})=>/^\s*\d{3,4}\s*$/.test(token.text)&&value>=300&&value<=6000);
  const horizontal=dimensions.filter(({token})=>!token.rotated).map(({value})=>value);const vertical=dimensions.filter(({token})=>token.rotated).map(({value})=>value);const allDimensions=dimensions.map(({value})=>value);
  const width=mode(horizontal.filter((value)=>value>=600))??mode(allDimensions.filter((value)=>value>=600))??Math.max(0,...allDimensions);const usefulVertical=[...new Set((vertical.length?vertical:allDimensions).filter((value)=>value>=600&&value!==width))].sort((a,b)=>b-a);const height=vertical.length&&usefulVertical.length>=3?usefulVertical[Math.floor(usefulVertical.length/2)]:usefulVertical.find((value)=>value<width)??usefulVertical[0];
  const items:Item[]=[];
  const add=(category:string,keyword:RegExp,reference:string)=>{if(!keyword.test(lower))return;const features=[/led strip/i.test(text)?"LED strip detail":null,/both sides/i.test(text)?"Both sides":null,/recessed/i.test(text)?"Recessed installation":null].filter(Boolean).join(" · ");const warnings=[!width?"Width was not found":null,!height?"Height was not found":null,`Confirm ${category.toLowerCase()} thickness and material type`,`Confirm quantity`].filter(Boolean) as string[];items.push({id:`${page}-${category.toLowerCase().replaceAll(" ","-")}`,reference,category,width:width?String(width):"",height:height?String(height):"",quantity:"1",specification:"Needs confirmation",features,sourcePage:page,sourceView:/section[-\s]?a/i.test(text)?"Section-A":"Drawing view",confidence:width&&height?74:52,method:"Drawing text",status:"review",warnings})};
  add("Mirror",/\bmirror\b/i,`M-P${page}`);add("Glass partition",/glass partition|shower screen|shower glass/i,`GP-P${page}`);add("Glass door",/glass door/i,`GD-P${page}`);add("Aluminium work",/aluminium|aluminum|metal frame|aluminium profile/i,`AL-P${page}`);return items;
}

export default function Home(){
  const picker=useRef<HTMLInputElement>(null);const [fileName,setFileName]=useState("");const [fileUrl,setFileUrl]=useState("");const [pageCount,setPageCount]=useState(0);const [activePage,setActivePage]=useState(1);const [items,setItems]=useState<Item[]>([]);const [selected,setSelected]=useState("");const [analyzing,setAnalyzing]=useState(false);const [analysisStep,setAnalysisStep]=useState(0);const [message,setMessage]=useState("Upload a plan, section, elevation, or detail drawing to begin.");const selectedItem=useMemo(()=>items.find((item)=>item.id===selected),[items,selected]);const warnings=items.reduce((sum,item)=>sum+item.warnings.length,0);
  useEffect(()=>()=>{if(fileUrl)URL.revokeObjectURL(fileUrl)},[fileUrl]);
  useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:"get_drawing_takeoff_summary",title:"Read drawing takeoff",description:"Read the visible drawing takeoff summary and unresolved review warnings.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({fileName,total:items.length,approved:items.filter(i=>i.status==="approved").length,warnings})},{signal:lifecycle.signal})).catch(console.error);return()=>lifecycle.abort()},[fileName,items,warnings]);
  function update(key:keyof Item,value:string){if(!selectedItem)return;setItems((current)=>current.map((item)=>item.id===selected?{...item,[key]:value,status:"review"}:item))}
  function addManual(){const item=emptyItem(String(Date.now()),activePage);setItems((current)=>[...current,item]);setSelected(item.id);setMessage("Manual item added. Complete and verify its details.")}
  function duplicate(){if(!selectedItem)return;const copy={...selectedItem,id:String(Date.now()),reference:`${selectedItem.reference}-COPY`,status:"review" as Status};setItems((current)=>[...current,copy]);setSelected(copy.id)}
  function remove(){if(!selectedItem)return;setItems((current)=>current.filter((item)=>item.id!==selected));setSelected("")}
  function approve(){if(!selectedItem)return;const unresolved=[!selectedItem.width?"Width is required":null,!selectedItem.height?"Height is required":null,!selectedItem.specification||selectedItem.specification==="Needs confirmation"?"Material specification is required":null].filter(Boolean) as string[];setItems((current)=>current.map((item)=>item.id===selected?{...item,warnings:unresolved,status:unresolved.length?"review":"approved"}:item));setMessage(unresolved.length?"Complete the highlighted information before approval.":`${selectedItem.reference} approved.`)}
  async function chooseFile(file?:File){
    if(!file)return;if(fileUrl)URL.revokeObjectURL(fileUrl);setFileName(file.name);setFileUrl(URL.createObjectURL(file));setItems([]);setSelected("");setActivePage(1);setAnalyzing(true);setAnalysisStep(1);setMessage("Opening drawing pages…");
    try{
      const pdfjs=await import("pdfjs-dist");pdfjs.GlobalWorkerOptions.workerSrc=new URL("pdfjs-dist/build/pdf.worker.min.mjs",import.meta.url).toString();
      const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;setPageCount(pdf.numPages);const found:Item[]=[];
      for(let pageNumber=1;pageNumber<=pdf.numPages;pageNumber++){
        setAnalysisStep(1);setMessage(`Reading page ${pageNumber} of ${pdf.numPages}…`);const page=await pdf.getPage(pageNumber);const content=await page.getTextContent();
        setAnalysisStep(2);let tokens:PositionedText[]=content.items.filter((entry)=>"str" in entry&&entry.str.trim()).map((entry)=>{const item=entry as {str:string;transform:number[]};return{text:item.str.trim(),x:item.transform[4],y:item.transform[5],rotated:Math.abs(item.transform[1])>Math.abs(item.transform[0])}});
        let proposed=inferItems(tokens,pageNumber);const needsDimensions=proposed.length===0||proposed.some((item)=>!item.width||!item.height);
        if(needsDimensions){
          try{setAnalysisStep(3);setMessage(`Scanning glass, aluminium, and mirror annotations on page ${pageNumber}…`);const base=page.getViewport({scale:1});const scale=Math.min(1.2,2600/Math.max(base.width,base.height));const viewport=page.getViewport({scale});const canvas=document.createElement("canvas");canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);const context=canvas.getContext("2d");
          if(context){await page.render({canvasContext:context,viewport}).promise;const {createWorker}=await import("tesseract.js");const worker=await createWorker("eng",undefined,{workerPath:"/tesseract-worker.min.js",workerBlobURL:false,langPath:"https://tessdata.projectnaptha.com/4.0.0_fast",logger:(progress)=>{if(progress.status==="recognizing text")setMessage(`Extracting drawing annotations · ${Math.round(progress.progress*100)}%`)}});const result=await worker.recognize(canvas);const rotated=document.createElement("canvas");rotated.width=canvas.height;rotated.height=canvas.width;const rotatedContext=rotated.getContext("2d");let rotatedText="";if(rotatedContext){rotatedContext.translate(rotated.width,0);rotatedContext.rotate(Math.PI/2);rotatedContext.drawImage(canvas,0,0);setMessage("Checking vertical dimensions…");rotatedText=(await worker.recognize(rotated)).data.text}await worker.terminate();const ocrTokens=`${result.data.text} ${rotatedText}`.split(/\s+/).filter(Boolean).map((text)=>({text,x:0,y:0,rotated:false}));tokens=[...tokens,...ocrTokens];proposed=inferItems(tokens,pageNumber)}}catch(ocrError){console.error("OCR fallback failed",ocrError);setMessage("Callouts were read, but plotted dimensions need manual confirmation.")}
        }
        found.push(...proposed);
      }
      setAnalysisStep(4);setItems(found);if(found[0]){setSelected(found[0].id);setActivePage(found[0].sourcePage);setMessage(`${found.length} work item${found.length===1?"":"s"} proposed. Verify the candidate dimensions and material details.`)}else setMessage("No glass, aluminium, or mirror callout was found. Add an item manually while reviewing the drawing.");
    }catch(error){console.error("PDF analysis failed",error);setMessage("The PDF pages could not be opened. The drawing remains available for manual takeoff.")}finally{setAnalyzing(false)}
  }
  function exportCsv(){const approved=items.filter((item)=>item.status==="approved");const rows=[["Reference","Category","Width (mm)","Height (mm)","Quantity","Specification","Features","Source page","Source view"],...approved.map((item)=>[item.reference,item.category,item.width,item.height,item.quantity,item.specification,item.features,String(item.sourcePage),item.sourceView])];const csv=rows.map((row)=>row.map((value)=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`${fileName.replace(/\.pdf$/i,"")||"drawing"}-takeoff.csv`;link.click();URL.revokeObjectURL(url)}
  if(!fileName)return <main className="welcome-shell"><header className="topbar"><Brand/><button className="button primary" onClick={()=>picker.current?.click()}><Upload size={17}/>Upload drawing</button></header><input ref={picker} type="file" accept="application/pdf" hidden onChange={(event)=>chooseFile(event.target.files?.[0])}/><section className="upload-card" onClick={()=>picker.current?.click()}><span className="upload-icon"><ScanLine size={32}/></span><p className="eyebrow">NEW DRAWING TAKEOFF</p><h1>Drop in the drawing you received</h1><p>Plans, sections, elevations, bathroom details, mirrors, glass partitions, and doors.</p><button className="button primary"><Upload size={18}/>Choose PDF</button><small>The drawing stays in your browser during analysis.</small></section></main>;
  return <main className="app-shell"><input ref={picker} type="file" accept="application/pdf" hidden onChange={(event)=>chooseFile(event.target.files?.[0])}/><header className="topbar"><Brand/><div className="file-pill"><FileText size={16}/>{fileName}</div><div className="top-actions"><button className="button ghost" onClick={()=>picker.current?.click()}><Upload size={17}/>Replace</button><button className="button primary" onClick={exportCsv} disabled={!items.some(i=>i.status==="approved")}><Download size={17}/>Export approved</button></div></header>
    <section className="workspace-head"><div><p className="eyebrow">DRAWING TAKEOFF</p><h1>Plans, sections & elevations</h1><p className="analysis-message">{analyzing&&<LoaderCircle size={14} className="spin"/>}{message}</p></div><div className="progress-copy"><strong>{items.length} proposed item{items.length===1?"":"s"}</strong><span>{items.filter(i=>i.status==="approved").length} approved · {warnings} open checks</span></div></section>
    <section className="workspace-grid"><aside className="pages-panel"><div className="panel-title"><span>Drawing pages</span><span className="count">{pageCount}</span></div>{Array.from({length:pageCount},(_,index)=>index+1).map((page)=><button key={page} className={`page-thumb ${activePage===page?"active":""}`} onClick={()=>setActivePage(page)}><span className="page-paper"><i/><i/><i/><b/></span><span>Page {page}<small>{items.some(i=>i.sourcePage===page)?"Takeoff item found":"Review drawing"}</small></span></button>)}</aside>
      <section className="drawing-panel"><div className="drawing-toolbar"><span><Layers3 size={16}/>Source drawing</span><span>Page {activePage} of {pageCount}</span></div><div className="drawing-stage"><iframe className="pdf-frame" src={`${fileUrl}#page=${activePage}&view=FitH`} title="Uploaded drawing PDF"/>{analyzing&&<div className="analysis-overlay"><div className="analysis-card"><LoaderCircle className="spin" size={26}/><p className="eyebrow">EXTRACTING WORKS</p><h2>{message}</h2><div className="phase-list"><span className={analysisStep>=1?"done":""}>1. Read drawing pages</span><span className={analysisStep>=2?"done":""}>2. Find glass, aluminium, and mirror callouts</span><span className={analysisStep>=3?"done":""}>3. Read plotted dimensions</span><span className={analysisStep>=4?"done":""}>4. Prepare items for review</span></div><small>Large CAD drawings can take a little longer on the first scan.</small></div></div>}</div></section>
      <aside className="review-panel"><div className="panel-title action-title"><span>Proposed work items</span><button onClick={addManual}><Plus size={15}/>Add item</button></div><div className="item-list">{items.map((item)=><button key={item.id} className={`item-row ${selected===item.id?"active":""}`} onClick={()=>{setSelected(item.id);setActivePage(item.sourcePage)}}><span className={`confidence ${item.confidence>=85?"high":item.confidence>=65?"medium":"low"}`}>{item.confidence}%</span><span><strong>{item.reference}</strong><small>{item.category} · Page {item.sourcePage}</small></span>{item.status==="approved"?<Check size={16} className="approved-icon"/>:item.warnings.length?<AlertTriangle size={16} className="warning-icon"/>:null}</button>)}</div>
        {selectedItem?<div className="editor"><div className="editor-head"><div><p className="eyebrow">TAKEOFF ITEM</p><h2>{selectedItem.reference}</h2></div><span className={selectedItem.status==="approved"?"approved-badge":"review-badge"}>{selectedItem.status==="approved"?"Approved":"Verify"}</span></div><div className="form-grid"><label>Reference<input value={selectedItem.reference} onChange={(e)=>update("reference",e.target.value)}/></label><label>Category<input value={selectedItem.category} onChange={(e)=>update("category",e.target.value)}/></label><label>Width <span>mm</span><input value={selectedItem.width} onChange={(e)=>update("width",e.target.value)}/></label><label>Height <span>mm</span><input value={selectedItem.height} onChange={(e)=>update("height",e.target.value)}/></label><label>Quantity<input value={selectedItem.quantity} onChange={(e)=>update("quantity",e.target.value)}/></label><label className="full">Material specification<input value={selectedItem.specification} onChange={(e)=>update("specification",e.target.value)}/></label><label className="full">Features / notes<input value={selectedItem.features} onChange={(e)=>update("features",e.target.value)}/></label></div>{selectedItem.warnings.length>0&&<div className="warnings"><AlertTriangle size={17}/><span><strong>Check before approval</strong>{selectedItem.warnings.join(" · ")}</span></div>}<div className="editor-actions"><button className="icon-button" onClick={duplicate} title="Duplicate"><Copy size={17}/></button><button className="icon-button danger" onClick={remove} title="Delete"><Trash2 size={17}/></button><button className="approve-button" onClick={approve}><Check size={18}/>Approve item</button></div></div>:<div className="empty-state"><ScanLine size={30}/><strong>No item selected</strong><span>Add a takeoff item manually or select an extracted proposal.</span><button className="button secondary" onClick={addManual}><Plus size={16}/>Add item</button></div>}
      </aside></section>
  </main>;
}
function Brand(){return <div className="brand"><span className="brand-mark"><ScanLine size={22}/></span><span><strong>EXO AI</strong><small>DRAWINGS EXTRACTOR</small></span></div>}
